language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install -r django_geoip/tests/requirements.pip
  - pip install . --use-mirrors
# command to run tests
script: python runtests.py